git:
  quiet: true
language: c
services:
  - docker

env:
  - DOCKER_USER=$DOCKER_USERNAME
  - DOCKER_PASS=$DOCKER_PASSWORD

jobs:
  include:
    - stage: build-with-tests
      script:
        - docker-compose build
        - docker-compose up -d
        - docker-compose exec app alembic upgrade head
        - docker-compose exec app python app/scripts/init_admin.py
        - docker-compose exec app pytest
        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        - docker-compose push app
stages:
  - build-with-tests
