git:
  quiet: true
language: python
services:
  - docker

env:
  - DOCKER_USER=$DOCKER_USERNAME
  - DOCKER_PASS=$DOCKER_PASSWORD

jobs:
  include:
    - stage: build
      script:
        - docker-compose build
    - stage: test
      script:
        - docker-compose up -d
        - docker-compose exec app alembic upgrade head
        - docker-compose exec app python app/scripts/init_admin.py
        - docker-compose exec app pytest
    - stage: publish
      script:
        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        - docker-compose push app

stages:
  - build
  - test
  - publish
