"""group_user cascade

Revision ID: 5575f09cb969
Revises: d92f76e85e94
Create Date: 2021-07-08 16:55:16.653698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5575f09cb969'
down_revision = 'd92f76e85e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_users_user_id_fkey', 'group_users', type_='foreignkey')
    op.drop_constraint('group_users_group_id_fkey', 'group_users', type_='foreignkey')
    op.create_foreign_key(None, 'group_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_users', 'user_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_users', type_='foreignkey')
    op.drop_constraint(None, 'group_users', type_='foreignkey')
    op.create_foreign_key('group_users_group_id_fkey', 'group_users', 'user_groups', ['group_id'], ['id'])
    op.create_foreign_key('group_users_user_id_fkey', 'group_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
