"""add permissions table

Revision ID: fc8880aa4860
Revises: f126b53d70f5
Create Date: 2021-06-24 12:26:56.638972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8880aa4860'
down_revision = 'f126b53d70f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
